#!/usr/bin/env bash

set -e

CONTAINER_VERSION=$1
AWS_ACCOUNT_ID=$2
AWS_REGION=$3

CONTAINER_NAME=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${PWD##*/}

echo "publishing to $CONTAINER_NAME"
eval $(aws ecr get-login --region $AWS_REGION)
docker push $CONTAINER_NAME
